# -*- mode: ruby -*-
# vi: set ft=ruby :
FRONT_BOX_PATH = 'front.box'
NGINX_BOX_PATH = 'nginx.box'
MIRROR_BOX_PATH = 'mirror.box'


Vagrant.configure("2") do |config|
 config.vm.synced_folder ".", "/synced"
 config.vm.define "front" do |subconfig|
   subconfig.vm.box = "front_server_sna"

   subconfig.vm.hostname = "front"
   subconfig.vm.network :private_network, ip: "10.0.0.11"
   subconfig.vm.network "forwarded_port", guest: 5000, host: 5000
   subconfig.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
   end
   config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("C:/Users/Dinislam/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
   end
 end

 config.vm.define "nginx" do |subconfig|
   subconfig.vm.box = "nginxbox"
   subconfig.vm.box_url = NGINX_BOX_PATH
   subconfig.vm.hostname = "nginx"
   subconfig.vm.network :private_network, ip: "10.0.0.12"
   subconfig.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
   end
 end

 config.vm.define "mirror1" do |subconfig|
   subconfig.vm.box = "mirrorbox"
   subconfig.vm.box_url = MIRROR_BOX_PATH
   subconfig.vm.hostname = "mirror1"
   subconfig.vm.network :private_network, ip: "10.0.0.13"
   subconfig.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
   end
 end

 config.vm.define "mirror2" do |subconfig|
   subconfig.vm.box = "mirrorbox"
   subconfig.vm.box_url = MIRROR_BOX_PATH
   subconfig.vm.hostname = "mirror2"
   subconfig.vm.network :private_network, ip: "10.0.0.14"
   subconfig.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
   end
 end

end